namespace: monk-cassandra

stack:
  defines: process-group
  runnable-list:
    - monk-cassandra/cassandra2
    - monk-cassandra/cassandra1
  variables:
    cassandra-cluster:
      type: string
      value: monk
    cassandra-password:
      type: string
      value: monk
